Fix delete all goals
cjs8487/PlayBingo pull request #42
Opened 2024-10-01 13:29 UTC by devbeoservice

-Added a delete all button with confirmation (github style) where user has to write 'DELETE' to get it done.
-Added axios to be required in web
-made a change in gitignore for convenience while developing, ignoring docker-compose.yaml

2024-10-01 15:28 UTC, devbeoservice commented
fixed as per requirements from https://discord.com/channels/503244944807559178/1237085818103922799/1290684943785005108 and https://discord.com/channels/503244944807559178/1237085818103922799/1290689245995995219

2024-10-02 23:16 UTC, cjs8487 requested changes
Overall comments
- SnackbarNotifier should be deleted
- The delete all button should probably be colocated with other controls at the top of the activity, along with the settings and upload buttons, especially since upload and delete all will often be used in tandem (at least until a "replace all" option is added for upload)
- Delete all should probably not be a contained button, though the error styling is semantically correct

2024-10-02 23:16 UTC, cjs8487 commented on web/src/components/game/goals/GoalManagement.tsx
> +            <Dialog ref={deleteDialogRef}>
If we're going to seat multiple dialogs into a single component we should either
a) make them each their own component, and utilize `useImperativeHandle`/`forwardRef` to isolate state/functionality
b) Use a modular composing system for the content so we only seat a single dialog and have a single ref, such as something like the following
```tsx
const [dialogContent, setDialogContent] = useState(null)
const launchDelateAllConfirmation = () => {
    setDialogContent(<DeleteAllConfirmationDialog />)
    dialogRef.current.open()
}
...
return (
    ...
    <Button onClick={launchDeleteAllConfirmation}
    <Dialog ref={dialogRef}>
        {dialogContent}
    </Dialog>
)
```

2024-10-02 23:16 UTC, cjs8487 commented on web/src/components/game/goals/GoalManagement.tsx
> +            <Dialog ref={deleteDialogRef}>
If a dialog requires it's own standalone state, it should usually be it's own component

2024-10-02 23:16 UTC, cjs8487 commented on web/src/components/game/goals/GoalManagement.tsx
> +            mutateGoals();
We should probably call `mutateGoals` in the finally block in order to catch corner cases where we get partial deletion before running into a database error or similar

2024-10-02 23:16 UTC, cjs8487 commented on api/src/routes/games/Games.ts
> +games.delete('/:slug/delete-all-goals', async (req, res) => {
Route names should be camelCased if they are multiple words

2024-10-02 23:16 UTC, cjs8487 commented on api/src/database/games/Goals.ts
> +export const deleteAllGameGoals = async (gameSlug: string) => {
Name this deleteAllGoalsForGame

2024-10-02 23:16 UTC, cjs8487 commented on web/src/components/game/goals/GoalManagement.tsx
> +                // Handle failure silently
This failure doesn't necessarily need to be silent, you can toast the message sent by the server if you feel it is appropriate (and safe) to do so. Generally, failure cases where the failure is not obvious should not fail silently

2024-10-02 23:16 UTC, cjs8487 commented on web/src/components/game/goals/GoalManagement.tsx
> +                            {loading ? 'Deleting...' : 'Delete All Goals'}
Having the delete dialog stay open, and having this loading/processing indicator feels redundant

2024-10-04 12:22 UTC, devbeoservice commented
resolved all except location of the button

2024-10-05 03:31 UTC, cjs8487 approved these changes

2024-10-05 03:35 UTC, merged